# Generated by Django 3.0.3 on 2020-02-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondboards', '0003_auto_20200214_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='photo',
            field=models.ImageField(blank=True, upload_to='buyphotos'),
        ),
    ]
