# Generated by Django 3.0.3 on 2020-02-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='photo',
            field=models.ImageField(blank=True, upload_to='sellphotos'),
        ),
    ]
